### ISSUE TITLE
Localize the documentation

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-help#305]
The issue to track what needs to be done in order to localize the documentation:

Of course I might miss some ideas. Feel free to edit this post or ask for additions.

### Minimal todo list

 - [x] change the structure of the repo (move the markdown files from `help/` to `help/en/docs` (done in #310)
 - [x] Weblate: add a project and add the Discovery Component addon
 - [x] Change the mkdocs configuration and add build script (done in #313)
 - [x] Add a serve script (done in #313)
 - [x] Be sure that every page not localized fallback or offer a redirection to the English page (done in #313)
 - [x] Adapt the gitlab action that pushes the documentation to netlify when opening PRs (probably done in #313)
 - [x] Link to the Weblate project so visitors are invited to help translating in `help/missing-translation.md` (done in #313)
 - [ ] Localize the titles of the sections and of the documents ([see comment](https://github.com/gristlabs/grist-help/pull/313#discussion_r1502523183))
 - [x] Add the select box to change the language (done in #313)

### Probably much worth to be done

 - [x] Support for screenshot localisation (done in #313)
 - [ ] Support screenshot localisation in Weblate instead of the VCS?
 - [ ] Be sure we can add specific pages for some languages
 - [ ] Localizing the tutorial (see [below](https://github.com/gristlabs/grist-help/issues/305#issuecomment-1946206027))

### Questions

 - [x] [Ability to add the tutorial on local instances like ANCT's ?](https://github.com/gristlabs/grist-help/issues/305#issuecomment-1946229417) (example of [tutorial](https://templates.getgrist.com/doc/woXtXUBmiN5T))
 - [x] Translate the tutorial ?
 - [ ] Is it possible to use a different language than English as a source? (like French → English)

**Comment by RaywanS** [comment]
Hey @fflorent ! In a ideal world, behavior would be like this : 

- if doc available in French, show french
- if doc not available in French, automatically switch in English and show a small banner on top of page explaining that "doc is not available in French yet, so we switched to english"

Do you think it will be something doable?

**Comment by RaywanS** [comment]
Also, can we add the tutorial localization ? Here is the link : https://templates.getgrist.com/doc/woXtXUBmiN5T~7p5UKv6PkqMT6EypW1VbJ3~32752

**Comment by RaywanS** [comment]
@fflorent me again : do you think it will be possible to integrate the tutorial from getgrist.com directly into the ANCT or incubateur instance ( after translating it ? )

**Comment by fflorent** [comment]
Hey @RaywanS !

> Hey @fflorent ! In a ideal world, behavior would be like this :

That's done :)
