### ISSUE TITLE
Follow-up localization

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-help#329]
Follow-up of #305 

## TODO: 
- [ ] Localize the titles of the sections and of the documents (#396) 
- [x] Use GitLocalize instead of Weblate (#370) 

## Probably much worth to be done

 - [ ] Support screenshot localisation in Weblate instead of the VCS?
 - [x] Be sure we can add specific pages for some languages

## Questions

- [x] Is it possible to use a different language than English as a source? (like French → English)

**Comment by fflorent** [comment]
>  Is it possible to use a different language than English as a source? (like French → English)

I feel like it won't be possible with GitLocalize.

>  Be sure we can add specific pages for some languages

That could be done, but by hacking with the code:
 - We can add new navigation items using the [mkdocs hooks](https://github.com/gristlabs/grist-help/blob/b54b8c16503230cbd5df8565b59fab5765e1fc46/mkdocs-utils/hooks.py) (using [on_nav](https://www.mkdocs.org/dev-guide/plugins/#on_nav));
   - We may use the [`extra`](https://www.mkdocs.org/user-guide/configuration/#extra) configuration item to declare any nav additional items;
 - The page should be added directly to the git repository;
